import type { PlaceMenuSeed } from "./types";

/**
 * Each place's menu, keyed by the place's slug: a heading, one line under it and nine
 * items. Non-restaurant places carry the menu of their café, kiosk, stall or shop. The
 * words are Brazilian Portuguese; each `photo` is an English brief for the image
 * generator, a realistic 3:4 photograph with no text in the frame.
 */
export const MENUS: Readonly<Record<string, PlaceMenuSeed>> = {
  "praca-do-pinhao": {
    title: "Café e barracas da praça",
    lede: "O café dos guarda-sóis abre cedo e as barracas de pinhão acendem o fogo no fim da tarde, quando a beira do lago enche de gente.",
    items: [
      {
        slug: "pinhao-na-panela-de-ferro",
        name: "Pinhão na panela de ferro",
        description: "Cozido com sal grosso na panela preta e servido quente no cone de papel, para comer olhando o lago.",
        tag: "Clássico",
        photo: "A paper cone of boiled pinhão (brown, thumb-sized araucaria seeds), a few split to show the cream kernel, held over a blackened cast-iron pot steaming on a wood fire. 45-degree close-up, turquoise lake blurred behind, late golden-hour light.",
      },
      {
        slug: "sapecada-de-pinhao",
        name: "Sapecada de pinhão",
        description: "Assado direto na grimpa em chamas, casca queimada por fora e macio por dentro, do jeito dos tropeiros.",
        tag: "Da estação",
        photo: "Pinhão seeds charred black on a bed of burning dry araucaria branches on the ground, a few pulled aside onto a rough plank with a small knife. Close-up at 45 degrees, flames and smoke glowing orange at dusk.",
      },
      {
        slug: "empadinha-de-pinhao",
        name: "Empadinha de pinhão",
        description: "Massa que desmancha e recheio de pinhão moído com frango e cheiro-verde, assada no forno do café.",
        photo: "Three small golden pies in fluted tins on a white enamel plate, one broken open to show a pinhão and chicken filling, on a café table under a canvas parasol. Close-up, soft afternoon light, lake and white bandstand blurred behind.",
      },
      {
        slug: "sorvete-de-pinhao",
        name: "Sorvete de pinhão",
        description: "Feito na casa com pinhão cozido e leite da serra, cor de café com leite e pedacinhos crocantes.",
        tag: "Da casa",
        photo: "Two scoops of pale beige pinhão ice cream with crunchy seed pieces in a small ceramic bowl, a spoon beside it, on a painted wooden café table. Close-up at 45 degrees, bright midday light, turquoise water blurred behind.",
      },
      {
        slug: "cafe-passado-na-hora",
        name: "Café passado na hora",
        description: "Coado no pano, servido em xícara de louça grossa com um pedaço de rapadura no pires.",
        photo: "Black coffee dripping through a cloth filter into a thick white porcelain cup, a piece of brown rapadura sugar on the saucer, on a lakeside café table. Close-up, soft morning light, steam rising.",
      },
      {
        slug: "cappuccino-com-canela",
        name: "Cappuccino com canela",
        description: "Leite vaporizado, cacau e canela em pau, para segurar com as duas mãos quando o vento vem do lago.",
        photo: "A wide ceramic cup of cappuccino dusted with cinnamon, a cinnamon stick on the saucer, held by two hands in wool gloves over a checked cloth. Overhead, cool late-afternoon light.",
      },
      {
        slug: "sonho-de-doce-de-leite",
        name: "Sonho de doce de leite",
        description: "Massa frita macia, recheio generoso de doce de leite e açúcar por cima, direto da vitrine do café.",
        photo: "A sugar-dusted fried Brazilian doughnut split open and filled with thick caramel-coloured doce de leite, on a white paper napkin on a café counter. Close-up at 45 degrees, warm window light.",
      },
      {
        slug: "bolo-de-cenoura",
        name: "Bolo de cenoura com chocolate",
        description: "Fatia alta com a cobertura de chocolate ainda mole, vendida no balcão até a forma acabar.",
        photo: "A tall slice of orange carrot cake with glossy soft chocolate icing on a small ceramic plate, a fork beside it, on a weathered café table under a parasol. Close-up, soft golden-hour light, lake blurred behind.",
      },
      {
        slug: "cha-de-maca-com-canela",
        name: "Chá de maçã com canela",
        description: "Maçã de São Joaquim fervida com canela e cravo, servida no copo de vidro nas noites da Festa do Pinhão.",
        photo: "A glass mug of hot apple and cinnamon tea with apple slices and cloves floating, on a wooden stall counter at night, string lights and a cast-iron pot blurred behind. Close-up, warm firelight and soft bokeh.",
      },
    ],
  },
  "galpao-do-fogo": {
    title: "Cardápio do galpão",
    lede: "Tudo sai da mesma brasa: a costela que entra de manhã, o cordeiro na vara e o abacaxi que fecha a mesa quando o fogo já baixou.",
    items: [
      {
        slug: "costela-de-fogo-de-chao",
        name: "Costela de fogo de chão",
        description: "Seis horas em vara de ferro sobre a brasa, só com sal grosso, cortada na tábua em frente à mesa.",
        tag: "Da casa",
        photo: "A whole slab of beef ribs on an iron rod leaning over glowing embers on an earth floor, fat dripping and crust dark brown, inside an open timber shed. 45-degree close-up, firelight and drifting smoke, dusk outside.",
      },
      {
        slug: "cordeiro-na-vara",
        name: "Cordeiro na vara",
        description: "Cordeiro da serra aberto em cruz na armação de ferro, quatro horas de calor de lado, sem pressa.",
        photo: "A butterflied lamb stretched on a cross-shaped iron frame beside a low open fire, skin golden and crackling. Close-up at 45 degrees, rough timber posts and smoke behind, orange firelight.",
      },
      {
        slug: "vazio-na-brasa",
        name: "Vazio na brasa",
        description: "O corte gaúcho da fraldinha, grelhado inteiro, servido rosado e fatiado contra a fibra.",
        photo: "Sliced flank steak, pink in the centre and charred at the edges, on a thick wooden board with coarse salt and a knife, on a rough timber table. Overhead, warm firelight.",
      },
      {
        slug: "farofa-de-pinhao",
        name: "Farofa de pinhão",
        description: "Pinhão cozido e picado na farinha de mandioca com bacon e cebola, para acompanhar a costela.",
        tag: "Clássico",
        photo: "A cast-iron pan of golden cassava-flour farofa with chopped pinhão (brown, thumb-sized araucaria seeds) and crisp bacon, a wooden spoon in it, on a rough timber table. 45-degree close-up, firelight from the side.",
      },
      {
        slug: "mandioca-na-manteiga",
        name: "Mandioca na manteiga",
        description: "Aipim cozido até abrir e depois dourado na manteiga, com sal e salsinha.",
        tag: "Vegetariano",
        photo: "Chunks of boiled cassava split open and golden with butter and parsley in a white enamel dish on a timber table. Close-up at 45 degrees, warm firelight, embers blurred behind.",
      },
      {
        slug: "salada-de-radicci",
        name: "Salada de radicci com bacon",
        description: "Radicci da horta em tiras finas, bacon quente e vinagre por cima, do jeito que se come na serra.",
        photo: "A ceramic bowl of finely shredded green chicory leaves dressed with hot bacon pieces and vinegar, on a checked cloth on a timber table. Overhead, warm late-afternoon light.",
      },
      {
        slug: "queijo-serrano-na-chapa",
        name: "Queijo serrano na chapa",
        description: "Fatia grossa de queijo serrano tostada na chapa de ferro até formar crosta, com orégano.",
        photo: "A thick slice of pale cured highland cheese seared golden on a small cast-iron griddle, oregano scattered on top, on a timber table. Close-up at 45 degrees, embers glowing behind.",
      },
      {
        slug: "chope-artesanal",
        name: "Chope artesanal de Lages",
        description: "Chope claro de uma cervejaria pequena da cidade, tirado na hora e servido no copo gelado.",
        photo: "A frosted glass of golden draft beer with a thick white head on a rough timber table, the embers of an open fire blurred behind. Close-up, warm firelight.",
      },
      {
        slug: "abacaxi-na-brasa",
        name: "Abacaxi na brasa com canela",
        description: "Fatias de abacaxi grelhadas no fim do fogo, com açúcar queimado e canela por cima.",
        photo: "Thick rings of pineapple on an iron grate over dying embers, caramelised sugar and cinnamon on top. Close-up at 45 degrees, deep orange firelight and a wisp of smoke.",
      },
    ],
  },
  "mirante-da-neblina": {
    title: "Café do mirante",
    lede: "Um balcão de madeira ao lado da plataforma de pedra, aberto desde as cinco, para quem sobe no escuro e espera a neblina cobrir o lago.",
    items: [
      {
        slug: "cafe-da-garrafa",
        name: "Café da garrafa",
        description: "Coado forte antes do amanhecer e levado na garrafa térmica até a pedra, com caneca esmaltada.",
        tag: "Clássico",
        photo: "Steaming black coffee poured from a vacuum flask into a white enamel mug on a stone ledge, a sea of fog covering a lake far below. Close-up, blue pre-dawn light turning pink on the horizon.",
      },
      {
        slug: "chocolate-quente-cremoso",
        name: "Chocolate quente cremoso",
        description: "Grosso de colher, feito com leite integral e cacau, para quem sobe no frio de junho.",
        tag: "Do inverno",
        photo: "Thick hot chocolate in a heavy ceramic mug, a spoon standing in it, on a wooden railing draped with a wool blanket. Close-up at 45 degrees, misty morning light, fog and araucaria silhouettes blurred behind.",
      },
      {
        slug: "torta-de-maca",
        name: "Torta de maçã",
        description: "Maçã de São Joaquim em fatias finas sobre massa amanteigada, servida morna com canela.",
        tag: "Da casa",
        photo: "A slice of apple pie with thin fanned apple slices and a golden crust on a small ceramic plate, a fork beside it, on a weathered wooden counter. 45-degree close-up, soft window light, fog outside the glass.",
      },
      {
        slug: "pao-na-chapa",
        name: "Pão na chapa",
        description: "Pão francês aberto e tostado na manteiga, crocante por fora, para acompanhar o café da garrafa.",
        photo: "A split bread roll toasted golden with melting butter on a small cast-iron griddle, on a rough wooden counter. Close-up, warm lamplight against a blue foggy dawn outside the window.",
      },
      {
        slug: "bolo-de-fuba",
        name: "Bolo de fubá com erva-doce",
        description: "Fatia úmida de bolo de milho com sementes de erva-doce, cortada da forma redonda logo cedo.",
        photo: "A slice of yellow cornmeal cake flecked with fennel seeds on a checked cloth napkin, the round cake in its tin behind. Overhead, soft misty window light.",
      },
      {
        slug: "mingau-de-aveia",
        name: "Mingau de aveia com mel",
        description: "Aveia cozida no leite com mel e canela, na tigela de louça que esquenta as mãos.",
        photo: "A ceramic bowl of hot oat porridge with a swirl of honey and cinnamon, a spoon on a wool blanket beside it, on a stone ledge. Overhead, pale blue dawn light, fog below.",
      },
      {
        slug: "biscoito-de-nata",
        name: "Biscoito de nata",
        description: "Biscoitinhos amanteigados feitos com nata da serra, vendidos no saquinho de papel pardo.",
        photo: "Small round butter cookies heaped in an open brown paper bag on a wooden counter, a few spilled out. Close-up at 45 degrees, soft morning light, a misty window behind.",
      },
      {
        slug: "misto-quente",
        name: "Misto quente",
        description: "Queijo serrano e presunto no pão de forma, prensados na chapa até o queijo escorrer.",
        photo: "A toasted ham and cheese sandwich cut diagonally, melted cheese oozing, on a white enamel plate on a rough wooden counter. Close-up, warm lamplight, fog outside the window.",
      },
      {
        slug: "pao-de-queijo",
        name: "Pão de queijo",
        description: "Assado em fornadas pequenas enquanto o sol não sai, casquinha por fora e quente por dentro.",
        photo: "A small wicker basket of golden cheese bread rolls, one torn open and steaming, on a wooden counter. Close-up at 45 degrees, soft misty daylight.",
      },
    ],
  },
  "bosque-das-araucarias": {
    title: "Quiosque da ilha",
    lede: "O quiosque fica no píer da ilha e monta a cesta antes da trilha: comida que aguenta a caminhada e cabe na mesa debaixo das araucárias.",
    items: [
      {
        slug: "cesta-da-ilha",
        name: "Cesta da ilha",
        description: "Cesta de vime com sanduíches, fruta, bolo e suco para dois, entregue no píer na chegada do barco.",
        tag: "Para dividir",
        photo: "An open wicker picnic basket with wrapped sandwiches, apples, a slice of cake and a glass bottle of juice, on a checked cloth over fallen pine needles. Overhead, dappled light through araucaria branches.",
      },
      {
        slug: "sanduiche-de-truta-defumada",
        name: "Sanduíche de truta defumada",
        description: "Truta da serra defumada no pão de centeio, com cream cheese, pepino e endro.",
        photo: "A rye bread sandwich with pink smoked trout, cucumber slices and dill, half unwrapped from waxed paper on a wooden picnic table. Close-up at 45 degrees, dappled forest light.",
      },
      {
        slug: "salada-de-pinhao-com-maca",
        name: "Salada de pinhão com maçã",
        description: "Pinhão cozido e descascado com maçã verde, folhas e molho de mel, no pote de vidro.",
        tag: "Vegetariano",
        photo: "A glass jar salad of peeled pinhão (thumb-sized araucaria seeds, brown-shelled and cream inside), green apple cubes and leaves, set on a mossy log. Close-up, soft light filtering through araucaria crowns.",
      },
      {
        slug: "quiche-de-alho-poro",
        name: "Quiche de alho-poró",
        description: "Massa amanteigada e recheio de alho-poró com queijo serrano, em fatia embrulhada para a trilha.",
        photo: "A wedge of leek and cheese quiche on a sheet of brown paper on a rough wooden bench. Close-up at 45 degrees, dappled light, tall araucaria trunks blurred behind.",
      },
      {
        slug: "suco-de-maca-com-gas",
        name: "Suco de maçã com gás",
        description: "Suco de maçã prensado e gaseificado, bem gelado, na garrafinha de vidro.",
        photo: "A small glass bottle of sparkling apple juice and a glass with bubbles rising, standing on a wooden pier post, a lake and an island of araucarias behind. Close-up, bright afternoon light.",
      },
      {
        slug: "chimarrao-para-a-trilha",
        name: "Chimarrão para a trilha",
        description: "Cuia, bomba, erva moída na hora e garrafa térmica cheia, devolvidos no píer na volta.",
        tag: "Para levar",
        photo: "A gourd of green chimarrão with a metal straw and a vacuum flask resting on an araucaria root, fallen needles around. Close-up at 45 degrees, soft forest light.",
      },
      {
        slug: "empanada-de-frango",
        name: "Empanada de frango",
        description: "Massa folhada assada com frango desfiado, azeitona e ovo, fácil de comer andando.",
        photo: "Two golden baked turnovers with crimped edges, one broken to show a shredded chicken filling, on a paper napkin on a picnic table. Close-up, dappled light through the trees.",
      },
      {
        slug: "morangos-com-nata",
        name: "Morangos com nata",
        description: "Morango da serra no pote, com nata batida por cima e uma pitada de açúcar.",
        photo: "A small glass jar of red strawberries topped with thick whipped cream, a wooden spoon resting on it, on a checked cloth. Overhead, soft green-tinted forest light.",
      },
      {
        slug: "pao-de-mel",
        name: "Pão de mel",
        description: "Bolinho de especiarias com mel e cobertura de chocolate, embrulhado para o bolso da jaqueta.",
        photo: "Chocolate-covered honey spice cakes, one cut in half, on a small wooden board on a mossy log. Close-up at 45 degrees, dappled light through araucaria branches.",
      },
    ],
  },
  "vinicola-de-altitude": {
    title: "Rótulos da cantina",
    lede: "Seis rótulos da encosta, colhidos depois do frio e servidos na cantina de pedra, com o que a serra põe na mesa ao lado da taça.",
    items: [
      {
        slug: "sauvignon-blanc",
        name: "Sauvignon Blanc",
        description: "Branco cítrico e fresco, com a acidez que só a noite fria da serra dá à uva.",
        photo: "A glass of pale straw-coloured white wine on a stone windowsill, condensation on the bowl, vine rows descending to a turquoise lake beyond. Close-up at 45 degrees, bright cool morning light.",
      },
      {
        slug: "pinot-noir",
        name: "Pinot Noir",
        description: "Tinto leve e claro, de fruta vermelha e terra úmida, das fileiras mais altas da encosta.",
        photo: "A glass of translucent ruby red wine held by a hand among vine rows on a hillside, grape leaves turning yellow. Close-up, golden-hour backlight.",
      },
      {
        slug: "cabernet-franc",
        name: "Cabernet Franc",
        description: "Tinto de pimentão e especiaria, doze meses em barrica, o rótulo que a cantina mais defende.",
        photo: "A glass of deep red wine on the head of an oak barrel in a cool stone cellar, a candle glowing beside it. Close-up at 45 degrees, warm dim light.",
      },
      {
        slug: "merlot",
        name: "Merlot",
        description: "Tinto macio de ameixa madura, que acompanha o queijo serrano sem brigar com ele.",
        photo: "Dark red wine being poured into a glass on a rough wooden table, a wedge of cured cheese beside it, a stone wall behind. Close-up, warm window light.",
      },
      {
        slug: "espumante-nature",
        name: "Espumante nature",
        description: "Método tradicional, dois anos sobre as borras, bolha fina e seco como a manhã de geada.",
        tag: "Da casa",
        photo: "Two flutes of sparkling wine with fine rising bubbles on a stone ledge, frost-white grass and vines blurred behind. Close-up, crisp early-morning light.",
      },
      {
        slug: "rose-de-merlot",
        name: "Rosé de Merlot",
        description: "Rosado cor de salmão, de prensagem direta, para a tarde na varanda com o lago lá embaixo.",
        photo: "A glass of pale salmon-pink rosé on a wooden veranda rail, a vineyard hillside and a turquoise lake below. Close-up at 45 degrees, warm late-afternoon light.",
      },
      {
        slug: "tabua-de-queijos-da-serra",
        name: "Tábua de queijos da serra",
        description: "Queijo serrano curado, colonial e de ovelha, com mel de melato e nozes.",
        tag: "Para dividir",
        photo: "A wooden board with wedges of cured highland cheese, a pale sheep cheese, walnuts and a small bowl of dark honeydew honey, beside two glasses of red wine on a stone table. Overhead, soft window light.",
      },
      {
        slug: "pinhao-na-manteiga-de-salvia",
        name: "Pinhão na manteiga de sálvia",
        description: "Pinhão descascado e dourado na frigideira com manteiga e sálvia, servido na tigela de barro.",
        photo: "Peeled pinhão (thumb-sized araucaria seeds, brown-shelled and cream inside) glazed in sage butter in a small clay bowl, crisp sage leaves on top, a glass of wine beside it. Close-up at 45 degrees, warm window light.",
      },
      {
        slug: "suco-de-uva-integral",
        name: "Suco de uva integral",
        description: "Da mesma uva dos tintos, sem açúcar e sem água, servido na taça como os outros.",
        tag: "Sem álcool",
        photo: "A wine glass of opaque dark purple grape juice on a stone table, a bunch of dark grapes beside it. Close-up, soft window light, vineyard rows blurred outside.",
      },
    ],
  },
  "ctg-porteira-do-tropeiro": {
    title: "Cozinha do CTG",
    lede: "A cozinha do galpão abre nas noites de baile e serve o que os tropeiros comiam na estrada, em panela de ferro e prato fundo.",
    items: [
      {
        slug: "arroz-carreteiro",
        name: "Arroz carreteiro",
        description: "Arroz com charque picado na ponta da faca, feito na panela de ferro sobre o fogão a lenha.",
        tag: "Clássico",
        photo: "A black cast-iron pot of rice with shredded dried beef and green onion, a wooden spoon in it, on a wood-burning stove. Close-up at 45 degrees, warm lamplight in a whitewashed hall.",
      },
      {
        slug: "feijao-campeiro",
        name: "Feijão campeiro",
        description: "Feijão preto com linguiça, bacon e farinha de mandioca, grosso de sustentar a noite inteira.",
        photo: "A deep plate of thick black beans with sausage, bacon and toasted cassava flour on a rough plank table. Overhead, warm lantern light.",
      },
      {
        slug: "churrasco-de-espeto",
        name: "Churrasco de espeto",
        description: "Carne de gado em espeto de madeira sobre a brasa, servida direto na tábua com sal grosso.",
        photo: "Chunks of beef on wooden skewers over glowing coals in a low brick pit, fat sizzling. Close-up at 45 degrees, firelight in a dim hall.",
      },
      {
        slug: "linguica-campeira",
        name: "Linguiça campeira",
        description: "Linguiça de porco temperada com alho e pimenta, assada em roda na brasa.",
        photo: "A coiled pork sausage browned over embers on an iron grill, a knife and coarse salt on a board beside it. Close-up, orange firelight.",
      },
      {
        slug: "mocoto-da-madrugada",
        name: "Mocotó da madrugada",
        description: "Caldo grosso de mocotó com feijão branco e linguiça, servido depois da meia-noite no baile.",
        tag: "Do inverno",
        photo: "A steaming bowl of thick beef-trotter stew with white beans and sausage on a timber table, a spoon beside it. Close-up at 45 degrees, late-night lantern light.",
      },
      {
        slug: "quentao-de-vinho",
        name: "Quentão de vinho",
        description: "Vinho tinto quente com gengibre, cravo e canela, servido na caneca de ágata na varanda.",
        photo: "A white enamel mug of hot spiced red wine with ginger slices and cloves on the wooden rail of a deep veranda at night, an iron lantern glowing behind. Close-up, warm lantern light.",
      },
      {
        slug: "cuca-de-uva",
        name: "Cuca de uva",
        description: "Massa fofa com uva inteira e farofa doce por cima, assada pelas prendas no forno do galpão.",
        tag: "Da casa",
        photo: "A slice of crumb cake topped with whole purple grapes and sugary streusel on a white enamel plate on a plank table. Close-up at 45 degrees, soft window light.",
      },
      {
        slug: "chimarrao-da-roda",
        name: "Chimarrão da roda",
        description: "Cuia de porongo e erva nova, passando de mão em mão enquanto a gaita não para.",
        photo: "A hand passing a gourd of chimarrão with a silver straw beside a soot-blackened kettle on a wood stove. Close-up, warm firelight in a whitewashed hall.",
      },
      {
        slug: "doce-de-abobora",
        name: "Doce de abóbora com cravo",
        description: "Abóbora em pedaços cozida no açúcar com cravo, servida fria no pratinho de vidro.",
        photo: "Glossy orange cubes of pumpkin in syrup with cloves in a small pressed-glass dish on a checked cloth. Close-up at 45 degrees, soft window light.",
      },
    ],
  },
  "estacao-velha": {
    title: "Bancas da plataforma",
    lede: "No sábado de manhã as bancas ocupam a plataforma inteira, debaixo da cobertura de zinco, e cada produtor vende o que fez na semana.",
    items: [
      {
        slug: "queijo-serrano-curado",
        name: "Queijo serrano curado",
        description: "De leite cru de gado de corte, curado sessenta dias na fazenda, vendido em peça ou em cunha.",
        tag: "Clássico",
        photo: "A whole wheel of pale yellow cured highland cheese with one wedge cut out, on a wooden market stall under a corrugated metal roof. Close-up at 45 degrees, soft misty morning light, old railway tracks blurred behind.",
      },
      {
        slug: "mel-de-melato",
        name: "Mel de melato de bracatinga",
        description: "Mel escuro de floresta, colhido nos anos de safra da bracatinga, menos doce e mais mineral.",
        tag: "Da estação",
        photo: "Jars of very dark amber honeydew honey on a wooden stall, a honey dipper dripping into one. Close-up, soft morning light, fog over railway tracks behind.",
      },
      {
        slug: "cuca-de-banana",
        name: "Cuca de banana",
        description: "Cuca alta de banana com farofa de canela, vendida inteira na forma ou em fatia.",
        photo: "A rectangular crumb cake with sliced bananas and cinnamon streusel in its baking tin on a market table, one slice lifted out. Overhead, soft morning light.",
      },
      {
        slug: "salame-colonial",
        name: "Salame colonial",
        description: "Salame de porco curado no porão, cortado na hora em fatia grossa para provar.",
        photo: "Cured salamis hanging from a wooden beam and one sliced on a board with a knife, on a market stall. Close-up at 45 degrees, cool morning light, an old station platform behind.",
      },
      {
        slug: "maca-fuji",
        name: "Maçã fuji de São Joaquim",
        description: "Do pomar a uma hora de estrada, em caixa de madeira, doce e crocante até o miolo.",
        photo: "Red and yellow striped apples heaped in a wooden crate on a market stall, a halved apple showing crisp white flesh. Close-up, soft misty morning light.",
      },
      {
        slug: "geleia-de-amora",
        name: "Geleia de amora",
        description: "Amora do mato cozida no tacho com pouco açúcar, no vidro com pano xadrez na tampa.",
        photo: "Jars of dark blackberry jam with checked cloth tied over the lids on a wooden stall, a spoonful spread on a slice of bread. Close-up at 45 degrees, soft morning light.",
      },
      {
        slug: "erva-mate",
        name: "Erva-mate moída na hora",
        description: "Erva nova do planalto, moída grossa para chimarrão e vendida no saco de papel.",
        tag: "Para levar",
        photo: "Bright green coarse-ground yerba mate heaped in an open paper sack with a metal scoop, on a wooden market stall. Close-up, soft morning light.",
      },
      {
        slug: "doce-de-figo",
        name: "Doce de figo em calda",
        description: "Figo verde inteiro cozido em calda escura, receita de vó, no vidro para levar para casa.",
        photo: "Whole green figs in dark glossy syrup in a glass jar and a small dish, on a checked cloth on a market table. Close-up at 45 degrees, soft light.",
      },
      {
        slug: "broa-de-milho",
        name: "Broa de milho",
        description: "Pão de fubá assado em forno de barro, casca dura e miolo amarelo, ainda morno às oito.",
        photo: "Round rustic cornbread loaves with cracked golden crusts stacked on a wooden table, one torn open to show the yellow crumb. Close-up at 45 degrees, cool morning light, a railway platform blurred behind.",
      },
    ],
  },
  "pousada-da-geada": {
    title: "Mesa da pousada",
    lede: "De manhã, café colonial na sala envidraçada; à noite, a mesa vai para perto da lareira e o lago escurece do outro lado da janela.",
    items: [
      {
        slug: "cafe-colonial-da-chegada",
        name: "Café colonial da chegada",
        description: "Cuca, pão caseiro, frios, geleias e bolo quente esperando na sala assim que as malas sobem.",
        photo: "A long table set for a colonial breakfast with crumb cake, bread, cold cuts, jam jars and a coffee pot, in a glazed room with frost on the lawn outside. 45-degree view, soft white morning light.",
      },
      {
        slug: "fondue-de-queijo-serrano",
        name: "Fondue de queijo serrano",
        description: "Queijo serrano derretido no vinho branco, com pão, batata e legumes para mergulhar.",
        tag: "Para dividir",
        photo: "A ceramic fondue pot of bubbling melted cheese over a small flame, bread cubes on long forks, beside a stone fireplace. Close-up at 45 degrees, warm firelight.",
      },
      {
        slug: "fondue-de-chocolate",
        name: "Fondue de chocolate",
        description: "Chocolate meio amargo derretido, com morango, banana e maçã para o fim da noite.",
        photo: "A small pot of melted dark chocolate with strawberries and apple pieces on forks around it, on a wooden table near a fire. Close-up, warm firelight and a dark background.",
      },
      {
        slug: "sopa-de-capeletti",
        name: "Sopa de capeletti",
        description: "Capeletti de frango feito à mão no caldo de galinha caipira, com queijo ralado por cima.",
        tag: "Do inverno",
        photo: "A steaming bowl of small hand-made stuffed pasta in clear golden chicken broth with grated cheese, on a wool placemat by a window onto a dark lake. Close-up at 45 degrees, lamplight.",
      },
      {
        slug: "creme-de-pinhao",
        name: "Creme de pinhão",
        description: "Pinhão cozido batido com caldo de legumes e nata, servido com croûtons e cebolinha.",
        photo: "A bowl of smooth beige soup made from pinhão (brown, thumb-sized araucaria seeds), with croutons and chives, a few whole seeds on the table beside it. Close-up at 45 degrees, warm firelight from a hearth.",
      },
      {
        slug: "sopa-de-abobora",
        name: "Sopa de abóbora com gengibre",
        description: "Abóbora cabotiá assada com gengibre e leite de coco, cremosa e sem carne nenhuma.",
        tag: "Vegetariano",
        photo: "A bowl of bright orange pumpkin soup with a swirl of cream and toasted seeds on a wooden tray, a wool blanket and a frosted window behind. Overhead, soft window light.",
      },
      {
        slug: "vinho-quente",
        name: "Vinho quente",
        description: "Vinho tinto da vinícola do lago aquecido com laranja, canela e cravo, servido junto da lareira.",
        photo: "A glass mug of steaming mulled red wine with an orange slice and a cinnamon stick on the stone hearth of a lit fireplace. Close-up, warm firelight.",
      },
      {
        slug: "omelete-de-queijo-serrano",
        name: "Omelete de queijo serrano",
        description: "Ovos da fazenda vizinha com queijo serrano e ervas da horta, feita na hora do café.",
        photo: "A folded golden omelette with melted cheese and chopped herbs on a white ceramic plate, a cup of coffee beside it, on a table by a window. Close-up at 45 degrees, bright morning light, frosty lawn outside.",
      },
      {
        slug: "ponche-quente-de-frutas",
        name: "Ponche quente de frutas",
        description: "Suco de uva, laranja e maçã aquecidos com especiarias, para quem quer a caneca sem o vinho.",
        tag: "Sem álcool",
        photo: "A ceramic mug of hot red fruit punch with apple and orange slices and a cinnamon stick, on the wooden arm of a chair draped with a wool blanket beside a fire. Close-up, warm firelight.",
      },
    ],
  },
  "fazenda-do-cedro": {
    title: "Café colonial da fazenda",
    lede: "A mesa vai para a varanda às nove e fica posta até perto do meio-dia, com o que a leiteria e a cozinha da casa branca fizeram.",
    items: [
      {
        slug: "mesa-do-cafe-colonial",
        name: "Mesa do café colonial",
        description: "Cuca de banana, melado, queijo, pão, nata e leite para a mesa inteira, repostos até a manhã acabar.",
        tag: "Para dividir",
        photo: "A farmhouse veranda table crowded with crumb cake, bread, a cheese wheel, jars of cane syrup and cream and a milk jug on a checked cloth, pasture and a red barn beyond. 45-degree view, bright morning light.",
      },
      {
        slug: "queijo-colonial-da-leiteria",
        name: "Queijo colonial da leiteria",
        description: "Feito com o leite das vacas da fazenda e curado quarenta dias na prateleira de madeira.",
        tag: "Da casa",
        photo: "Rows of small pale yellow cheese wheels curing on wooden shelves in a whitewashed dairy room, one cut open on a board. Close-up at 45 degrees, soft side light from a window.",
      },
      {
        slug: "melado-de-cana",
        name: "Melado de cana",
        description: "Melado grosso fervido no tacho, para comer com queijo ou com nata no pão.",
        photo: "Thick dark amber sugarcane syrup drizzled from a spoon over a slice of white cheese on bread, a glass jar behind. Close-up, warm morning light on a farmhouse table.",
      },
      {
        slug: "cafe-com-leite-da-ordenha",
        name: "Café com leite da ordenha",
        description: "Leite tirado de manhã, fervido na leiteira e misturado ao café de coador na xícara grande.",
        photo: "A large enamel mug of milky coffee next to a dented aluminium milk jug on a wooden veranda table, cows grazing in the pasture blurred behind. Close-up at 45 degrees, early morning light.",
      },
      {
        slug: "pao-caseiro-com-nata",
        name: "Pão caseiro com nata",
        description: "Fatia grossa de pão de forno a lenha com nata fresca da leiteria e açúcar por cima.",
        photo: "A thick slice of rustic bread spread with thick yellow farm cream and a sprinkle of sugar on a wooden board. Close-up, warm window light on a farmhouse table.",
      },
      {
        slug: "manteiga-da-fazenda",
        name: "Manteiga batida na fazenda",
        description: "Manteiga de nata batida à mão, levemente salgada, no pote de barro para levar.",
        tag: "Para levar",
        photo: "A block of pale yellow hand-churned butter in a small clay pot with a butter knife, beside bread on a checked cloth. Close-up at 45 degrees, soft morning light.",
      },
      {
        slug: "iogurte-natural",
        name: "Iogurte natural com granola",
        description: "Iogurte de leite integral da fazenda com granola de aveia e mel, no pote de vidro.",
        photo: "A glass jar of thick white yogurt topped with oat granola and a drizzle of honey, on a wooden veranda rail, green pasture blurred behind. Close-up, bright morning light.",
      },
      {
        slug: "requeijao-de-corte",
        name: "Requeijão de corte",
        description: "Requeijão firme e dourado, feito no tacho, para fatiar e esquentar na chapa.",
        photo: "A golden-browned block of firm cooked cheese sliced on a wooden board, one slice seared on a small griddle. Close-up at 45 degrees, warm farmhouse kitchen light.",
      },
      {
        slug: "bolo-de-milho-verde",
        name: "Bolo de milho verde",
        description: "Feito com o milho da roça ralado na hora, úmido e amarelo, cortado em quadrados.",
        photo: "Squares of moist yellow fresh-corn cake on a white enamel tray, a husked corn cob beside it, on a checked tablecloth. Overhead, soft morning light.",
      },
    ],
  },
  "fazenda-santa-barbara": {
    title: "Receitas da sede",
    lede: "O caderno de receitas da família está na cozinha desde 1912, e o fogão a lenha ainda é o mesmo que a bisavó acendia de madrugada.",
    items: [
      {
        slug: "quirera-com-costelinha",
        name: "Quirera com costelinha",
        description: "O prato de Lages: milho quebrado cozido devagar com costelinha de porco, na panela de ferro.",
        tag: "Clássico",
        photo: "A cast-iron pot of creamy cracked-corn stew with pork ribs on an old wood-burning stove, a ladle resting on the rim. Close-up at 45 degrees, warm light from a small window in a wooden kitchen.",
      },
      {
        slug: "galinha-caipira-com-pirao",
        name: "Galinha caipira com pirão",
        description: "Galinha do terreiro ensopada com açafrão e servida com pirão feito no próprio caldo.",
        photo: "A clay dish of stewed free-range chicken in golden turmeric sauce beside a bowl of smooth cassava porridge, on a worn wooden table. Overhead, soft window light.",
      },
      {
        slug: "pacoca-de-charque",
        name: "Paçoca de charque no pilão",
        description: "Charque desfiado e socado no pilão com farinha, a comida que os tropeiros levavam na garupa.",
        tag: "Da casa",
        photo: "Shredded dried beef pounded with cassava flour in a heavy wooden mortar, the pestle resting inside, on an old plank floor. Close-up at 45 degrees, warm window light, leather saddlery blurred behind.",
      },
      {
        slug: "sagu-de-vinho",
        name: "Sagu de vinho com creme",
        description: "Bolinhas de sagu cozidas no vinho tinto com cravo e cobertas de creme de baunilha.",
        photo: "A glass bowl of translucent purple tapioca pearls in red wine topped with pale vanilla custard, on a lace doily on a wooden table. Close-up, soft window light.",
      },
      {
        slug: "ambrosia",
        name: "Ambrosia",
        description: "Doce de ovos e leite talhado na calda com cravo, do jeito que a bisavó ensinou.",
        photo: "A small porcelain bowl of golden curdled egg-and-milk sweet in syrup with cloves, a copper pan blurred beside it on an old wooden table. Close-up at 45 degrees, soft window light.",
      },
      {
        slug: "cafe-no-fogao-a-lenha",
        name: "Café no fogão a lenha",
        description: "Coado no pano e mantido na chaleira sobre a chapa, oferecido a quem entra na cozinha.",
        photo: "A soot-blackened kettle and a cloth coffee filter on the iron top of a wood-burning stove, a cup of coffee on the edge. Close-up, warm firelight from the open firebox.",
      },
      {
        slug: "doce-de-leite-de-tacho",
        name: "Doce de leite de tacho",
        description: "Leite da ordenha da tarde mexido quatro horas no tacho de cobre, no pote de vidro.",
        tag: "Para levar",
        photo: "Thick glossy caramel-brown doce de leite stirred with a long wooden paddle in a copper pan. Close-up at 45 degrees, warm light from a farmhouse window.",
      },
      {
        slug: "polenta-na-chapa",
        name: "Polenta na chapa com queijo",
        description: "Fatias de polenta firme douradas na chapa do fogão e cobertas com queijo serrano.",
        photo: "Golden slices of grilled polenta topped with melting cheese on the iron plate of a wood-burning stove. Close-up at 45 degrees, warm firelight.",
      },
      {
        slug: "cha-de-marcela",
        name: "Chá de marcela",
        description: "Marcela colhida no campo na Sexta-feira Santa, como manda a tradição, na xícara de louça.",
        photo: "A porcelain cup of pale golden herbal tea beside a bundle of dried yellow marcela flowers on a wooden windowsill, pasture outside. Close-up, soft morning light.",
      },
    ],
  },
  "fazenda-dos-pinheiros": {
    title: "Tudo do pinhão",
    lede: "Na safra, de abril a julho, a cozinha da fazenda só trabalha com o que cai das araucárias, e o resto do ano vive do que guardou.",
    items: [
      {
        slug: "pinhao-da-safra",
        name: "Pinhão da safra",
        description: "Catado no chão do pinheiral na mesma semana e vendido cru, no saco de ráfia de um quilo.",
        tag: "Da estação",
        photo: "A burlap sack spilling fresh raw pinhão (brown, thumb-sized araucaria seeds) onto the forest floor among fallen needles and a broken pine cone. Close-up at 45 degrees, soft morning light under araucaria crowns.",
      },
      {
        slug: "farinha-de-pinhao",
        name: "Farinha de pinhão",
        description: "Pinhão cozido, seco ao sol e moído fino, para bolo, pão e para engrossar o caldo.",
        tag: "Para levar",
        photo: "A wooden bowl of fine beige pinhão flour with a scoop, whole brown seeds scattered around, on a rough timber table. Overhead, soft window light.",
      },
      {
        slug: "pacoca-de-pinhao",
        name: "Paçoca de pinhão",
        description: "O prato da safra na serra: pinhão moído e refogado com carne moída, bacon e cheiro-verde.",
        tag: "Clássico",
        photo: "A cast-iron pan of ground pinhão sautéed with minced beef, bacon and green onion, a wooden spoon in it, on a timber table. Close-up at 45 degrees, warm window light, araucarias outside.",
      },
      {
        slug: "bolo-de-pinhao",
        name: "Bolo de pinhão",
        description: "Feito com a farinha da casa, úmido e cor de avelã, servido em fatia com café.",
        photo: "A slice of moist hazelnut-brown pinhão cake on a ceramic plate, a few whole seeds beside it and a cup of coffee, on a checked cloth. Close-up at 45 degrees, soft window light.",
      },
      {
        slug: "conserva-de-pinhao",
        name: "Conserva de pinhão",
        description: "Pinhão descascado em salmoura com alho e louro, no vidro, para durar até a safra seguinte.",
        photo: "Glass jars of peeled cream-coloured pinhão seeds in brine with garlic and bay leaves, lined up on a wooden shelf. Close-up, soft side light from a window.",
      },
      {
        slug: "nhoque-de-pinhao",
        name: "Nhoque de pinhão",
        description: "Massa de pinhão e batata feita à mão, servida na manteiga com queijo serrano ralado.",
        photo: "Hand-rolled beige gnocchi made with pinhão in brown butter and grated cheese in a shallow ceramic bowl. Close-up at 45 degrees, warm window light on a timber table.",
      },
      {
        slug: "pao-de-pinhao",
        name: "Pão de pinhão",
        description: "Pão de forno a lenha com farinha de pinhão na massa e pedaços do pinhão cozido no miolo.",
        photo: "A round rustic loaf cut open to show a tan crumb dotted with pinhão pieces, on a floured wooden board beside a wood-fired oven. Close-up at 45 degrees, warm light.",
      },
      {
        slug: "pe-de-moleque-de-pinhao",
        name: "Pé de moleque de pinhão",
        description: "Pinhão tostado preso na calda de açúcar mascavo, quebrado em lascas e vendido no saquinho.",
        photo: "Shards of amber brittle packed with toasted pinhão pieces on parchment on a wooden board. Close-up, soft window light.",
      },
      {
        slug: "licor-de-pinhao",
        name: "Licor de pinhão",
        description: "Pinhão tostado curtido na cachaça com açúcar queimado, servido em cálice no fim da colheita.",
        photo: "A small glass of amber liqueur beside a plain glass bottle and toasted pinhão seeds on a wooden table, araucaria trunks blurred through the window. Close-up at 45 degrees, golden-hour light.",
      },
    ],
  },
  "parque-caveiras": {
    title: "Barracas do parque",
    lede: "Os quiosques da alameda acendem junto com as lâmpadas do parque e vendem o que se come andando, entre a roda-gigante e o carrossel.",
    items: [
      {
        slug: "pastel-de-carne",
        name: "Pastel de carne",
        description: "Massa fina frita na hora, estufada e crocante, com carne moída, ovo e azeitona.",
        tag: "Clássico",
        photo: "A large golden fried pastel split open to show a ground beef filling, on waxed paper on a stall counter, fairground lights blurred behind. Close-up at 45 degrees, warm night bokeh.",
      },
      {
        slug: "churros-de-doce-de-leite",
        name: "Churros de doce de leite",
        description: "Frito na frente de quem pede, passado no açúcar com canela e recheado até a ponta.",
        photo: "Two sugar-coated churros filled with caramel doce de leite in a paper sleeve, a lit Ferris wheel blurred behind. Close-up, evening light and colourful bokeh.",
      },
      {
        slug: "quentao",
        name: "Quentão",
        description: "Cachaça com gengibre, cravo e açúcar queimado, fervida no tacho e servida na caneca de ágata.",
        tag: "Do inverno",
        photo: "A steaming enamel mug of hot ginger and clove spirit on a wooden stall counter, a large copper pot behind, carousel lights blurred in the night. Close-up, warm light.",
      },
      {
        slug: "maca-do-amor",
        name: "Maçã do amor",
        description: "Maçã de São Joaquim no palito, com calda de açúcar vermelha e dura como vidro.",
        photo: "Glossy bright red candied apples on sticks lined up on a stall tray, one bitten, colourful fairground lights blurred behind. Close-up at 45 degrees, night bokeh.",
      },
      {
        slug: "algodao-doce",
        name: "Algodão-doce",
        description: "Fiado na hora na máquina da barraca, rosa e maior que a cabeça de quem segura.",
        photo: "A large pink cotton candy on a stick held up by a hand against a lit Ferris wheel at dusk. Close-up, blue-hour light and warm bokeh.",
      },
      {
        slug: "pipoca-de-panela",
        name: "Pipoca de panela",
        description: "Estourada na panela de ferro com manteiga, salgada ou doce de caramelo, no saquinho de papel.",
        tag: "Para dividir",
        photo: "Popcorn overflowing from a paper bag beside a cast-iron pot on a stall counter under warm string lights. Close-up at 45 degrees, night light.",
      },
      {
        slug: "milho-cozido",
        name: "Milho cozido na manteiga",
        description: "Espiga inteira tirada do caldeirão, com manteiga derretida e sal.",
        photo: "A steaming boiled corn cob on a stick brushed with melting butter and salt, held over a stall counter. Close-up, warm light, a carousel blurred behind at dusk.",
      },
      {
        slug: "cachorro-quente",
        name: "Cachorro-quente",
        description: "Pão macio, salsicha no molho de tomate, batata palha e milho, do jeito do interior.",
        photo: "A Brazilian hot dog in a soft bun with sausage in tomato sauce, shoestring potato sticks and corn, wrapped in a paper napkin. Close-up at 45 degrees, amusement park lights blurred behind at night.",
      },
      {
        slug: "morango-com-chocolate",
        name: "Morango com chocolate",
        description: "Espeto de morangos da serra mergulhados no chocolate ao leite, ainda escorrendo.",
        photo: "A wooden skewer of strawberries dipped in dripping milk chocolate, held above a stall counter, a lit carousel blurred behind. Close-up, colourful night bokeh.",
      },
    ],
  },
  "deck-do-lago": {
    title: "Cardápio do deck",
    lede: "A cozinha trabalha com a truta dos tanques da serra e o pinhão da safra, e a mesa fica sobre a água até o sol sumir atrás do mirante.",
    items: [
      {
        slug: "truta-grelhada-na-brasa",
        name: "Truta grelhada na brasa",
        description: "Truta inteira dos tanques da serra, com manteiga de ervas e batata ao murro.",
        tag: "Da casa",
        photo: "A whole grilled rainbow trout with herb butter and smashed roasted potatoes on a white plate on a wooden deck table, a turquoise lake behind. Close-up at 45 degrees, golden-hour light.",
      },
      {
        slug: "risoto-de-pinhao",
        name: "Risoto de pinhão",
        description: "Arroz arbóreo cremoso com pinhão picado, queijo serrano e um fio de manteiga tostada.",
        photo: "A shallow bowl of creamy risotto with chopped pinhão (brown, thumb-sized araucaria seeds, cream inside), shaved cheese and browned butter, on a wooden table by the lake. Close-up at 45 degrees, warm sunset light.",
      },
      {
        slug: "entrevero-de-pinhao",
        name: "Entrevero de pinhão",
        description: "Pinhão, carne de gado, porco, frango, linguiça e pimentão salteados juntos na chapa de ferro.",
        tag: "Clássico",
        photo: "A sizzling cast-iron skillet of mixed meats, peppers, onion and peeled pinhão seeds, a wooden spoon in it, on a lakeside deck table. Close-up at 45 degrees, golden-hour light.",
      },
      {
        slug: "carpaccio-de-truta",
        name: "Carpaccio de truta",
        description: "Lâminas finas de truta curada no sal e no limão, com alcaparras e azeite, para abrir a mesa.",
        photo: "Thin slices of pink cured trout fanned on a slate plate with capers, olive oil and small herbs, beside a glass of white wine. Overhead, soft evening light over a lake.",
      },
      {
        slug: "menu-do-por-do-sol",
        name: "Menu do pôr do sol",
        description: "Entrada, truta ou risoto e sobremesa para dois, com a garrafa da vinícola, servido às cinco.",
        tag: "Para dividir",
        photo: "A lakeside deck table set for two with plates of trout and risotto, a plain unlabelled bottle of red wine and two glasses, the sun low over turquoise water. 45-degree view, golden sunset light.",
      },
      {
        slug: "caipirinha-de-bergamota",
        name: "Caipirinha de bergamota",
        description: "Bergamota da serra macerada com açúcar e cachaça, no copo baixo com muito gelo.",
        photo: "A short glass of caipirinha with muddled tangerine wedges and crushed ice on the wooden rail of a deck, a lake at sunset behind. Close-up, golden backlight.",
      },
      {
        slug: "maca-e-gengibre-com-tonica",
        name: "Maçã e gengibre com tônica",
        description: "Suco de maçã prensado, gengibre fresco e tônica, com a cor e o gelo de um drinque de verdade.",
        tag: "Sem álcool",
        photo: "A tall glass of pale golden apple and ginger tonic with ice, apple slices and a coin of ginger, on a deck rail over the water. Close-up, warm sunset light.",
      },
      {
        slug: "pavlova-com-amoras",
        name: "Pavlova com amoras",
        description: "Suspiro crocante por fora, chantili e amora do mato, desmanchando na colher.",
        photo: "A crisp white meringue nest topped with whipped cream and dark blackberries on a ceramic plate on a wooden deck table, the lake blurred behind. Close-up at 45 degrees, soft dusk light.",
      },
      {
        slug: "creme-brulee-de-erva-mate",
        name: "Crème brûlée de erva-mate",
        description: "Creme de baunilha com infusão de erva-mate e casquinha de açúcar queimado no maçarico.",
        photo: "A ramekin of crème brûlée with a cracked caramel top and a spoon, a pinch of green yerba mate beside it, on a wooden table by the lake. Close-up, warm dusk light.",
      },
    ],
  },
  "ovni-porto": {
    title: "Cardápio de bordo",
    lede: "A lanchonete da torre abre quando escurece e dá nome de céu a lanche de estrada, para aguentar a madrugada no pátio de concreto.",
    items: [
      {
        slug: "disco-voador",
        name: "Disco voador",
        description: "Sanduíche de queijo e presunto prensado na chapa redonda até virar um disco dourado e fechado.",
        tag: "Da casa",
        photo: "A round sealed toasted sandwich, golden and disc-shaped, cut in half to show melted cheese and ham, on a white enamel plate on a metal table. Close-up at 45 degrees, cool bluish lamplight at night.",
      },
      {
        slug: "asteroides",
        name: "Asteroides",
        description: "Bolinhos de chuva fritos na hora, tortos como pedra do espaço, passados no açúcar com canela.",
        photo: "A paper cone of irregular fried dough balls rolled in cinnamon sugar on a concrete ledge, a starry night sky blurred behind. Close-up, warm lamplight against deep blue night.",
      },
      {
        slug: "buraco-negro",
        name: "Buraco negro",
        description: "Chocolate quente amargo, escuro e grosso, que puxa a colher para o fundo da caneca.",
        tag: "Do inverno",
        photo: "Almost black, thick hot chocolate in a dark enamel mug seen from above, a spoon sinking into it, on a wool blanket. Overhead, cool lamplight at night.",
      },
      {
        slug: "aneis-de-saturno",
        name: "Anéis de Saturno",
        description: "Rosquinhas de polvilho assadas, leves e crocantes, vendidas no saco para a vigília inteira.",
        photo: "Light, crunchy tapioca-starch rings spilling from a paper bag onto a concrete surface, small ground lights glowing blurred in the dark. Close-up at 45 degrees, night light.",
      },
      {
        slug: "combustivel-de-foguete",
        name: "Combustível de foguete",
        description: "Café coado bem forte na garrafa térmica de um litro, para ninguém dormir antes do avistamento.",
        photo: "Black coffee pouring from a steel vacuum flask into an enamel mug on a concrete ledge, a clear starry sky and the silhouette of a small control tower behind. Close-up, cool night light.",
      },
      {
        slug: "cratera",
        name: "Cratera",
        description: "Pão italiano redondo escavado e cheio de sopa de feijão quente, com a tampa servindo de colher.",
        photo: "A round crusty bread bowl filled with steaming bean soup, its cut lid resting beside it, on a metal table. Close-up at 45 degrees, warm lamplight against a dark night.",
      },
      {
        slug: "via-lactea",
        name: "Via Láctea",
        description: "Leite quente com mel de melato e canela, na caneca que esquenta as mãos no frio do pátio.",
        photo: "A white enamel mug of hot milk with a swirl of dark honey and a cinnamon stick, held by gloved hands under a starry sky. Close-up, soft cool night light, the Milky Way blurred behind.",
      },
      {
        slug: "estrela-cadente",
        name: "Estrela cadente",
        description: "Biscoito amanteigado em forma de estrela, coberto de açúcar de confeiteiro, vendido por dúzia.",
        photo: "Star-shaped butter cookies dusted with icing sugar on a dark metal tray, crumbs scattered. Overhead, cool bluish lamplight at night.",
      },
      {
        slug: "kit-abducao",
        name: "Kit abdução",
        description: "Cuia, erva, garrafa térmica e cobertor de lã, tudo emprestado para a madrugada no pátio.",
        tag: "Para levar",
        photo: "A gourd of chimarrão, a vacuum flask and a folded wool blanket laid on a concrete landing pad, small ground lights glowing along its edge. Close-up at 45 degrees, deep blue night light.",
      },
    ],
  },
  "salto-caveiras": {
    title: "Quiosque do salto",
    lede: "O quiosque fica na trilha entre a usina e as mesas de piquenique, e tudo o que vende aguenta ir de mão em mão até debaixo das araucárias.",
    items: [
      {
        slug: "cesta-de-piquenique",
        name: "Cesta de piquenique",
        description: "Queijo serrano, salame, pão de casa, fruta e suco para dois, com a mesa reservada.",
        tag: "Para dividir",
        photo: "A wicker basket open on a wooden picnic table with a wedge of cheese, sliced salami, a rustic loaf and apples, araucaria trunks and waterfall mist blurred behind. 45-degree view, dappled late-morning light.",
      },
      {
        slug: "sanduiche-de-pernil",
        name: "Sanduíche de pernil",
        description: "Pernil assado e desfiado no pão francês, com vinagrete e o molho do próprio assado.",
        photo: "A crusty bread roll stuffed with shredded roast pork and tomato-onion vinaigrette, half wrapped in paper, on a picnic table. Close-up at 45 degrees, dappled light.",
      },
      {
        slug: "bolinho-de-pinhao",
        name: "Bolinho de pinhão",
        description: "Pinhão cozido e moído com queijo, empanado e frito, servido em porção de dez.",
        tag: "Da casa",
        photo: "A paper tray of golden fried croquettes made from pinhão (brown, thumb-sized araucaria seeds), one broken open, a few whole seeds beside it on a wooden table. Close-up, soft daylight, a waterfall blurred behind.",
      },
      {
        slug: "maionese-de-batata",
        name: "Maionese de batata",
        description: "Batata, cenoura e ervilha com maionese caseira, no pote para levar até a mesa.",
        tag: "Vegetariano",
        photo: "A bowl of creamy potato salad with carrot and peas on a checked cloth on a picnic table under araucarias. Overhead, dappled light.",
      },
      {
        slug: "limonada-com-hortela",
        name: "Limonada com hortelã",
        description: "Limão espremido, hortelã e gelo na jarra de vidro, para o dia de sol na beira do rio.",
        photo: "A glass jug of lemonade with mint leaves and ice, beaded with condensation, on a wooden picnic table, the river blurred behind. Close-up, bright midday light.",
      },
      {
        slug: "picole-de-uva",
        name: "Picolé de uva",
        description: "Picolé caseiro de uva da serra, roxo e azedinho, tirado do freezer do quiosque.",
        photo: "A deep purple homemade grape ice pop on a wooden stick held by a hand against a blurred waterfall and green foliage. Close-up, bright sunlight.",
      },
      {
        slug: "bolo-de-laranja",
        name: "Bolo de laranja",
        description: "Fatia de bolo de laranja com calda, embrulhada no guardanapo para comer olhando a queda.",
        photo: "A slice of orange cake glazed with syrup on a paper napkin on a wooden deck rail, a waterfall and an old brick powerhouse blurred behind. Close-up at 45 degrees, morning light.",
      },
      {
        slug: "romeu-e-julieta",
        name: "Romeu e Julieta",
        description: "Queijo serrano com goiabada cascão em cubos, no palito, para a sobremesa do piquenique.",
        photo: "Cubes of pale cheese and dark red guava paste on toothpicks on a small wooden board on a picnic table. Close-up at 45 degrees, dappled light through araucarias.",
      },
      {
        slug: "salada-de-frutas",
        name: "Salada de frutas da serra",
        description: "Maçã, morango, pera e uva picados na hora no copo, com suco de laranja por cima.",
        photo: "A clear cup of chopped apple, strawberry, pear and grapes in orange juice with a small spoon on a picnic table. Close-up, bright daylight, river and araucarias blurred behind.",
      },
    ],
  },
};
